#!/usr/bin/env python
import sys
import random
import logging
logging.getLogger("scapy.runtime").setLevel(logging.ERROR)
from scapy.all import *
import warnings
warnings.filterwarnings("ignore")

ipAdd = sys.argv[1]
interface = sys.argv[2]
type = sys.argv[3]
message = sys.argv[4:]

message = ' '.join(message)
print message
if len(sys.argv) < 5:
    sys.exit()
if len(message) > 255:
    sys.exit()

chars = [ord(i) for i in message]

randomId = random.randint(65, 93)
num = 0
chars.append(0)
for c in chars:
    if (c == 0):
        num = len(chars)-1
        flag = 1<<12
        num=num+flag
        c = 0

    c = c<<8
    id = c + randomId
    msg = IP(dst = ipAdd, id = id,frag = num )
    if type == "0":
        msg = msg/ICMP()
    elif type == "1":
        msg = msg/TCP(dport = 80, flags = "S")
    elif type == "2":
        msg = msg/UDP(dport = 53)

    else:
        sys.exit(1)
    print hexdump(msg)
    send(msg,iface=interface)
    num = num+1

