#!/usr/bin/env python
import sys
import random
import logging
logging.getLogger("scapy.runtime").setLevel(logging.ERROR)
from scapy.all import *
import warnings
import os
os.system("gpg --import yugarsi.pub")

